vti_encoding:SR|utf8-nl
vti_author:SR|lenovo-PC\\lenovo
vti_modifiedby:SR|lenovo-PC\\lenovo
vti_timelastmodified:TR|28 Jan 2024 07:53:04 -0000
vti_timecreated:TR|24 May 2020 11:33:35 -0000
vti_title:SR|FEEDBACK
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|COLLECTION/DIAMOND\\ JEWELLERY/NECKLACE/Untitled_5.html MAIN\\ PAGES/GOLD\\ JEWELLERY.html COLLECTION/GOLD/BARS\\ &\\ COINS/GOLD\\ BARS.html COLLECTION/DIAMOND\\ JEWELLERY/TANMANIYA/mangalsutra.html COLLECTION/GOLD/BANGLES/GOLD\\ BANGLES3.html COLLECTION/GOLD/BANGLES/GOLD\\ BANGLES2.html COLLECTION/GOLD/EARRINGS/GOLD\\ EARRINGS.html COLLECTION/GOLD/PENDANT\\ SET/GOLD\\ PENDANT\\ SET.html COLLECTION/DIAMOND\\ JEWELLERY/TANMANIYA/TANMANIYA.html ABOUT\\ US/ABOUT\\ US.html COLLECTION/DIAMOND\\ JEWELLERY/EARRINGS/EARRINGS.html COLLECTION/SILVER/SILVER\\ BARS\\ &\\ COINS.html COLLECTION/GOLD/KIDS\\ WEAR/KIDS\\ WEAR.html COLLECTION/GOLD/NECKLACE/GOLD\\ NECKLACE2.html COLLECTION/GOLD/RINGS/GOLD\\ RINGS.html MAIN\\ PAGES/DIAMOND\\ JEWELLERY.html MAIN\\ PAGES/DIAMOND\\ JEWELLERY\\ 1.html MAIN\\ PAGES/DIAMOND\\ JEWELLERY\\ 1.dwt COLLECTION/DIAMOND\\ JEWELLERY/RINGS/RINGS4.html COLLECTION/DIAMOND\\ JEWELLERY/EARRINGS/EARRINGS2.html COLLECTION/DIAMOND\\ JEWELLERY/NOSEPIN/Untitled_5.html COLLECTION/DIAMOND\\ JEWELLERY/PENDANTS/PENDANTS.html COLLECTION/GOLD/BANGLES/GOLD\\ BANGLES.html index.html COLLECTION/DIAMOND\\ JEWELLERY/BRACELET/BRACELET.html COLLECTION/DIAMOND\\ JEWELLERY/RINGS/RINGS2.html COLLECTION/DIAMOND\\ JEWELLERY/RINGS/RINGS3.html COLLECTION/DIAMOND\\ JEWELLERY/BANGLES/BANGLES.html COLLECTION/GOLD/NECKLACE/GOLD\\ NECKLACE.html
vti_nexttolasttimemodified:TW|27 Jan 2024 08:42:20 -0000
vti_cacheddtm:TX|28 Jan 2024 07:53:04 -0000
vti_filesize:IR|4307
vti_cachedtitle:SR|FEEDBACK
vti_cachedbodystyle:SR|<body>
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|true
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=windows-1252 HTTP-EQUIV=Content-Language en-us
vti_charset:SR|windows-1252
vti_language:SR|en-us
